title: Renlong WANG
# tagline: Here is personal website of Renlong WANG. Powered by Jekyll, based on the Minimal Mistakes theme.
# description: Two roads diverged in woods, I took the one less traveled by.
#Comment out url when working locally to resolve base urls correctly
url: https://Renlong-WANG.github.io 

# Owner/author information
owner:
  name: Renlong WANG
  avatar: CVPHOTO.jpg
  bio: M.S. at University of Chinese Academy of Sciences
  location: Beijing, P.R.China
  email: 13127073530@163.com
  # cv: https://caihanlin.com/file/CV-HanlinCAI.pdf
  # scholar: https://scholar.google.com/citations?user=8igSoWgAAAAJ
  researchgate: https://www.researchgate.net/profile/Renlong-Wang-2
  orcid : https://orcid.org/0000-0002-6144-6028
  

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Conference Presentations
    url: /conference-presentations/
  - title: Awards
    url: /awards/
  - title: projects
    url: /projects/


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# Latest update in 2023/12/10 by Hanlin Cai.
