type = "card"
title = "Awards"

[[items]]
title = "Honors"
content = """
- National Scholarship for Postgraduates (Master) 2025.11
- Excellent Prize for the President Scholarship of Chinese Academy of Sciences 2025.04
- National Scholarship for Postgraduates (Master) 2024.11
- Merit Student of the University of Chinese Academy of Sciences 2024.07
- Distinguished Graduates in Civil Engineering from Jiangsu Universities and Colleges 2023.06
"""

[[items]]
title = "Conference Paper Awards"
content = """
- Excellent Paper Award in 2024 Student Academic Forum of the University of Chinese Academy of Sciences 2024.12
- Best Paper First Prize in 2024 International Symposium on Emergency Management 2024.11
- Excellent Paper Award in 2024 POMS Summer School in China 2024.08
- Best Paper Third Prize in 2023 International Symposium on Emergency Management 2023.11
- Excellent Paper Award in 2023 POMS Summer School in China 2023.08
"""

[[items]]
title = "Competition Awards"
content = """
- Outstanding Winner Prize of American Undergraduate Mathematical Contest in Modeling 2022.05
  - Highest award for the undergraduate mathematical contest in modeling in America; Top 0.16% among 27,205 teams
- SIAM Award of American Undergraduate Mathematical Contest in Modeling 2022.05
  - Six teams worldwide designated by The Society for Industrial and Applied Mathematics (SIAM)
- First Prize of Contemporary Undergraduate Mathematical Contest in Modeling 2021.10
  - Highest award for the undergraduate mathematical contest in modeling in China; Top 0.65% among 45,075 teams
"""