[site]
title = "Renlong WANG (王人龙) @ Rice CEE"
description = "Incoming Ph.D. student in Civil Engineering at Rice University."
favicon = "/favicon.svg"
last_updated = "June 30, 2026"

[author]
name = "Renlong WANG"
title = "Incoming Ph.D. Student"
institution = "Civil Engineering @ Rice University"
avatar = "/RLWANG.png"

[social]
email = "13127073530@163.com"
google_scholar = "https://scholar.google.com/citations?user=HwDGjnMAAAAJ"
orcid = "https://orcid.org/0000-0002-6144-6028"
github = "https://github.com/Renlong-WANG"
linkedin = "https://www.linkedin.com/in/renlong-wang-0b41aa379"

[features]
enable_likes = false
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
mode = "fixed"
fixed_locale = "en"
persist = false
switcher = false

[i18n.labels]
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"


[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"
