[[news]]
date = "2026-31"
content = "Ph.D. in Civil Engineering, Rice University, Houston, Texas, USA (expected)."

[[news]]
date = "2023-26"
content = "Master in Industrial Engineering and Management, University of Chinese Academy of Sciences, Beijing, China."

[[news]]
date = "2019-23"
content = "Bachelor in Civil Engineering, Nanjing Tech University, Nanjing, China."