[[news]]
date = "2026-2031"
content = "Ph.D. in Civil Engineering, Rice University, Houston, TX, USA (expected)."

[[news]]
date = "2023-2026"
content = "M.S. in Industrial Engineering and Management, University of Chinese Academy of Sciences, Beijing, China."

[[news]]
date = "2019-2023"
content = "B.Eng. in Civil Engineering, Nanjing Tech University, Nanjing, China."