[[news]]
date = "2026.05"
content = "My Google Scholar citations reached 100."

[[news]]
date = "2026.04"
content = "One sole-author paper was accepted by Annals of Operations Research."

[[news]]
date = "2026.04"
content = "One co-authored paper was accepted by Chinese Journal of Management Science."

[[news]]
date = "2026.03"
content = "I will join Rice University as a Ph.D. student in Civil Engineering in August 2026, advised by Dr. Jamie Padgett."

[[news]]
date = "2026.03"
content = "One first-author paper was accepted by Risk Analysis."

[[news]]
date = "2026.01"
content = "One corresponding-author paper was accepted by Scientific Reports."

[[news]]
date = "2025.12"
content = "One paper was recognized as a CNKI Highly Cited Paper."

[[news]]
date = "2025.11"
content = "I was honored with the National Scholarship for Postgraduates (Master)."

[[news]]
date = "2025.09"
content = "One corresponding-author paper was accepted by Energy."

[[news]]
date = "2025.09"
content = "One first-author paper was accepted by Simulation Modelling Practice and Theory."

[[news]]
date = "2025.05"
content = "One first-author paper was accepted by Expert Systems with Applications."

[[news]]
date = "2025.04"
content = "I was honored with the Excellent Prize for the President Scholarship of Chinese Academy of Sciences."