type = "card"
title = "Professional Services"

[[items]]
title = "Journal Reviewer"
date = "Ongoing"
content = "- AI and Ethics\n- BMC Methods\n- Chinese Journal of Management Science\n- Discover Applied Sciences\n- Frontiers in Environmental Science\n- International Journal of Computational Intelligence Systems\n- International Journal of Data Science and Analytics\n- Scientific Reports\n- Transportation Research Part E: Logistics and Transportation"