type = "card"
title = "Professional Services"

[[items]]
title = "Journal Reviewer"
date = "Ongoing"
content = "- AI and Ethics (2026 × 1)\n- BMC Methods (2026 × 1)\n- Chinese Journal of Management Science (2023 × 1, 2024 × 2, 2026 × 1)\n- Discover Applied Sciences (2026 × 1)\n- Frontiers in Environmental Science (2026 × 1)\n- International Journal of Computational Intelligence Systems (2026 × 1)\n- International Journal of Data Science and Analytics (2026 × 1)\n- Scientific Reports (2026 × 1)\n- Transportation Research Part E: Logistics and Transportation (2023 × 1)"