name: Get Citation Data

on:
  page_build:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: run google scholar crawler
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          echo "进入 google_scholar_crawler 目录"
          cd ./google_scholar_crawler

          echo "安装 Python 依赖"
          pip3 install -r requirements.txt

          echo "开始运行 Google Scholar crawler"
          python3 main.py

          echo "查看生成结果"
          ls -la ./results

          echo "准备推送结果到 google-scholar-stats 分支"
          cd ./results
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add *.json
          git commit -m "Updated Citation Data" || echo "No changes to commit"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:google-scholar-stats --force